
In this notebook, <br/>


1] The tweets were assigned new annotations performed in "relabelling iteration2" by matching tweet IDs from the original dataset with the Iteration2 (hate/non-hate) ids and storing the results in a new column, New_Label_iter2. <br/>

2] The [New_label] column stores relabeled annotations from iteration 1. For tweets that were not relabeled in this iteration, the values from [Original_label] are copied into [New_label]. <br/>

3] The [New_label_iter2] column stores relabeled annotations from iteration 2. For tweets that were not relabeled in this iteration, the values from the [New_label] column are copied into [New_label_iter2]. <br/>

4] The [Mismatch] column was assigned a value of 1 if either (A) the original annotations stored in [Original Label] differed from the iteration-1 relabeling annotations stored in [New_Label], or (B) the original annotations stored in [Original Label] differed from the iteration-2 relabeling annotations stored in [New_Label_iter2].

In [1]:
import pandas as pd
import numpy as np

In [2]:

train_df = pd.read_csv("dataset/Hindi_Alltasks.csv")
train_df= train_df.dropna(how='all')

In [3]:
train_df.head(20)

,text_id,tweet,Original_label,task_2,task_3,New_label,Mismatch
0,hasoc_hi_5556,"बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...",NOT,NONE,NONE,NOT,0
1,hasoc_hi_5648,सब रंडी नाच देखने मे व्यस्त जैसे ही कोई #शांती...,HOF,PRFN,UNT,HOF,0
2,hasoc_hi_164,तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...,HOF,PRFN,TIN,HOF,0
3,hasoc_hi_3530,"बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...",NOT,NONE,NONE,NOT,0
4,hasoc_hi_5206,चमकी बुखार: विधानसभा परिसर में आरजेडी का प्रदर...,NOT,NONE,NONE,NOT,0
5,hasoc_hi_5121,मुंबई में बारिश से लोगों को काफी समस्या हो रही है,NOT,NONE,NONE,NOT,0
6,hasoc_hi_7142,Ahmed's dad:-- beta aaj teri mammy kyu nahi ba...,NOT,NONE,NONE,NOT,0
7,hasoc_hi_4321,"5 लाख मुसलमान उर्स में, अजमेर की दरगाह पर आते ...",NOT,NONE,NONE,NOT,0
8,hasoc_hi_4674,"Do mahashaktiyan mili hain, charo taraf khusi ...",NOT,NONE,NONE,NOT,0
9,hasoc_hi_1637,Chants of 'Jai Sri Ram' as Owaisi takes oath: ...,NOT,NONE,NONE,NOT,0
10,hasoc_hi_5771,नृत्य होगा..! संगीत होगा..! जीवन मे उत्सव हो...,NOT,NONE,NONE,NOT,0
11,hasoc_hi_288,गाये के नाम पर जुल्म करने वालों तुम्हारी औकात ...,NOT,NONE,NONE,HOF,1
12,hasoc_hi_1803,डॉ. मुखर्जी ने एक देश में दो विधान दो प्रधान औ...,NOT,NONE,NONE,NOT,0
13,hasoc_hi_5900,धार्मिक पदों पर बैठे कुछ लोग अपने को भगवान समझ...,NOT,NONE,NONE,NOT,0
14,hasoc_hi_5951,सिक्का मोहब्बत का उछाल रक्खा है ~ हाँ मगर खुद...,NOT,NONE,NONE,NOT,0
15,hasoc_hi_1723,कोन कहता है आँखो में प्यार नही होता। जो डूब...,NOT,NONE,NONE,NOT,0
16,hasoc_hi_1691,"वैसे शपथ के अंत में ' जय भारत,जय संविधान' बोलन...",NOT,NONE,NONE,NOT,0
17,hasoc_hi_2070,"एक लंबे अंतराल के बाद आपके बीच #MannKiBaat, जन...",NOT,NONE,NONE,NOT,0
18,hasoc_hi_6865,"#नीच'समानार्थी शब्द #मोदी' दिला तर चालेल की, ल...",HOF,OFFN,TIN,HOF,0
19,hasoc_hi_918,डॉक्टर की लिखी 7 दिन की दवा के बजाय 3 दिन की...,NOT,NONE,NONE,NOT,0

In [4]:
mismatch_count = (train_df["Mismatch"] == 1).sum()
print("Count of relabelled tweets before iteration2 relabelling is",mismatch_count)

Count of relabelled tweets before iteration2 relabelling is 325

IDs of relabelled tweets that should be labeled as hate.

In [5]:
#hate_ids=[ 1441, 2419, 2420, 2506,2760, 2768, 2784, 3223,3474,3751,4378,4424 ] (2420 already relabelled HOF in first iteration)
hate_ids=[ 1441, 2419, 2506,2760, 2768, 2784, 3223,3474,3751,4378,4424 ]

In [6]:
#### create the label column if it doesn't exist
####train_df["New_label_iter2"] = None

##### compute the doubled hate_ids
double_hate_ids = [(i - 2) for i in hate_ids]

#### assign "HOF" where train_df index matches 2 * hate_ids
train_df.loc[train_df.index.isin(double_hate_ids), "New_label_iter2"] = "HOF"

In [7]:
print("The size of Iteration 2 tweets that have been relabelled as HOF.",len(train_df[train_df["New_label_iter2"]=="HOF"]))

The size of Iteration 2 tweets that have been relabelled as HOF. 11

In [8]:
train_df[train_df["New_label_iter2"]=="HOF"]

,text_id,tweet,Original_label,task_2,task_3,New_label,Mismatch,New_label_iter2
1439,hasoc_hi_7629,#बाॅर्डर पर क्या खूब कहा हमारे जवान ने पाक जवा...,NOT,NONE,NONE,NOT,0,HOF
2417,hasoc_hi_2388,कल जो दिल्ली में ये मुल्ला लोग मन्दिर में घुस ...,NOT,NONE,NONE,NOT,0,HOF
2504,hasoc_hi_4262,लेकिन एक बात पर विश्वास हो गया कि मणिशंकर अय्य...,NOT,NONE,NONE,NOT,0,HOF
2758,hasoc_hi_3629,आज भी #मोदी #नीच आदमी है:- #मणिशंकर_अय्यर वो ...,NOT,NONE,NONE,NOT,0,HOF
2766,hasoc_hi_3825,आज ये बात पक्की हो गई कि #भडवा कलर sorry #भगवा...,NOT,NONE,NONE,NOT,0,HOF
2782,hasoc_hi_4418,"कोई #मस्जिद टूटी होती तो कांग्रेस,विपक्ष,पाकि...",NOT,NONE,NONE,NOT,0,HOF
3221,hasoc_hi_7269,एक बात और बताऊँ। कोई अगर इसको आंटी बोल देता है...,NOT,NONE,NONE,NOT,0,HOF
3472,hasoc_hi_725,चर्च पर पत्थर फेंका किसी ने तो UN तक दौड़े जाए...,NOT,NONE,NONE,NOT,0,HOF
3749,hasoc_hi_4186,"#शेरो के काफिले में #कुत्ते अच्छे नही लगते, #...",NOT,NONE,NONE,NOT,0,HOF
4376,hasoc_hi_4796,18 साल का सैनिक शहीद हुआ तो वह बच्चा नहीं था औ...,NOT,NONE,NONE,NOT,0,HOF
4422,hasoc_hi_2426,"#प्रज्ञा_ठाकुर का पुतला जलाना ही पड़ेगा अब, बह...",NOT,NONE,NONE,NOT,0,HOF

In [9]:
#print(train_df.loc[2418, 'tweet'])

IDs of relabelled tweets that should be labeled as NOT

In [10]:
non_hate_ids=[1120,1125,1192,1415,1567,1828, 1848, 1875,1895,1916,1941, 1950, 1988, 1993, 1996, 2299,2862,2940,2944,2963,2984,3061,3087, 3102,3198,3375, 3485,3534,3573,3694,3750,3804,3922, 3935, 3976, 4216,4279, 4283,4563 ]
#1565 already labelled NOT in iteration1

In [11]:


##### compute the doubled hate_ids
double_nonhate_ids = [(i - 2) for i in non_hate_ids]

##### assign "HOF" where train_df index matches 2 * hate_ids
train_df.loc[train_df.index.isin(double_nonhate_ids), "New_label_iter2"] = "NOT"

In [12]:
print("The size of Iteration 2 tweets that have been relabelled as NOT",len(train_df[train_df["New_label_iter2"]=="NOT"]))

The size of Iteration 2 tweets that have been relabelled as NOT 39

In [13]:
train_df[train_df["New_label_iter2"]=="NOT"]

,text_id,tweet,Original_label,task_2,task_3,New_label,Mismatch,New_label_iter2
1118,hasoc_hi_6305,यूपी को अपराधमुक्त एवं भ्रष्टाचारमुक्त बनाने ह...,HOF,HATE,TIN,HOF,0,NOT
1123,hasoc_hi_6447,चौराहे के बीचों बीच बैठ के हमने #HanumanChalis...,HOF,HATE,TIN,HOF,0,NOT
1190,hasoc_hi_1767,"5 लाख मुसलमान उर्स में, अजमेर की दरगाह पर आते ...",HOF,HATE,UNT,HOF,0,NOT
1413,hasoc_hi_5749,श्री तबरेज अंसारी असाधारण प्रतिभा के धनी तो थे...,HOF,HATE,TIN,HOF,0,NOT
1565,hasoc_hi_2899,क्या ये लिंचिंग नहीं है??? मरने वाला हिन्दू...,HOF,OFFN,UNT,HOF,0,NOT
1826,hasoc_hi_1586,हम भारतीय बासी रोटी तो खा सकते हैं किन्तु ये 5...,HOF,HATE,TIN,HOF,0,NOT
1846,hasoc_hi_5367,क्या @narendramodi ऐसे भाजप के सांसद की बयान-ब...,HOF,HATE,TIN,HOF,0,NOT
1873,hasoc_hi_6924,तबरेज अंसारी के निधन से देश को बहुत बड़ी अपूर्...,HOF,HATE,TIN,HOF,0,NOT
1893,hasoc_hi_6020,मीडिया बस मोदी के एक-एक बात को पकड़ के ट्वीट क...,HOF,HATE,TIN,HOF,0,NOT
1914,hasoc_hi_5056,कहीं दलितों को मारा जा रहा है तो कहीं मुस्लिमो...,HOF,OFFN,TIN,HOF,0,NOT
1939,hasoc_hi_6821,आप ठीक से चौकेदारी नही कर पा रहे आपके द्वारा U...,HOF,HATE,TIN,HOF,0,NOT
1948,hasoc_hi_7522,"और उनका क्या जो लोग मुर्दो (मुर्गा, बकरी, गाय,...",HOF,HATE,TIN,HOF,0,NOT
1986,hasoc_hi_4742,BJP नेता रेप कर दे तो कोई देशभक्त नही बनता?? ...,HOF,OFFN,TIN,HOF,0,NOT
1991,hasoc_hi_4054,मैं कांग्रेस से पूछना चाहता हूँ कि जमायते इस्ल...,HOF,OFFN,TIN,HOF,0,NOT
1994,hasoc_hi_1736,जिस अनुप्रिया पटेल को आज मंत्री ना बनाकर कुर्म...,HOF,OFFN,TIN,HOF,0,NOT
2297,hasoc_hi_4203,"एक उंगली के चोट पे ट्वीट हो जाता है, थोड़ी सी ...",HOF,OFFN,TIN,HOF,0,NOT
2860,hasoc_hi_1727,महात्मा गांधी ने दिल्ली स्थित मंदिर में अपनी प...,HOF,HATE,TIN,HOF,0,NOT
2938,hasoc_hi_2242,अगर ईवीएम का भारत के देशवासियों विपक्षी पार्टि...,HOF,HATE,TIN,HOF,0,NOT
2942,hasoc_hi_867,पहले गोरो को हराया फिर हरमखोरों को हराया ...,HOF,PRFN,UNT,HOF,0,NOT
2961,hasoc_hi_378,"बाप एंकर की “औक़ात” बता रहा था,और अदालत ने बेट...",HOF,OFFN,UNT,HOF,0,NOT
2982,hasoc_hi_2843,तीन तलाक का कानून बनाने की जरूरत नही है अक्ल क...,HOF,HATE,TIN,HOF,0,NOT
3059,hasoc_hi_7796,खून तो हिन्दू और मुसलमान दोनों का लाल होता ...,HOF,HATE,TIN,HOF,0,NOT
3085,hasoc_hi_1542,"एबीपी न्यूज़ की टीम 9 जून को हमला करने वाले,, ...",HOF,HATE,TIN,HOF,0,NOT
3100,hasoc_hi_4764,आज सरकार कश्मीर समस्या पर तो बहस करना चाहती है...,HOF,HATE,TIN,HOF,0,NOT
3196,hasoc_hi_822,न्यूजीलैंड के 350 ईसाईयो ने उसी मस्जिद मे क़बू...,HOF,HATE,TIN,HOF,0,NOT
3373,hasoc_hi_5451,सभी साथियों से विनती पूर्वक कहता हु की 15%मुस्...,HOF,HATE,TIN,HOF,0,NOT
3483,hasoc_hi_6546,ये मीडिया जिन हिन्दुओ के सहारे चल रहा है उनके ...,HOF,HATE,UNT,HOF,0,NOT
3532,hasoc_hi_7386,कल कांग्रेस को संसद मे एकाएक लगा होगा कि इससे ...,HOF,HATE,TIN,HOF,0,NOT
3571,hasoc_hi_2131,"अनपढ़ मेरे #गाँव का, #गाय चराबन जाए। पढ़ा-लि...",HOF,HATE,UNT,HOF,0,NOT
3692,hasoc_hi_2403,"कालनेमि, जिन चीजों पे खतरा मंडरा रहा है: @Ra...",HOF,HATE,TIN,HOF,0,NOT
3748,hasoc_hi_1196,एक बात हैं ये बात सारे मेकी सेक्युलर नेता/नेत...,HOF,HATE,UNT,HOF,0,NOT
3802,hasoc_hi_6499,चूड़ियों की खनक में राग बन गए तुम पायलों की झ...,HOF,HATE,TIN,HOF,0,NOT
3920,hasoc_hi_7453,@MehboobaMufti अगर रंग का असर इतना होता है कि ...,HOF,OFFN,UNT,HOF,0,NOT
3933,hasoc_hi_1814,नेताओ को वोट चाहिए.. जो भी फ़ैसला होगा.. वो वो...,HOF,OFFN,UNT,HOF,0,NOT
3974,hasoc_hi_539,@DrKumarVishwas सर कहीं ये भी #हिंदी वही वाली ...,HOF,OFFN,UNT,HOF,0,NOT
4214,hasoc_hi_7360,। इस वीडियो पर ज्यादा टिप्पणी ना करें क्योंकि ...,HOF,OFFN,UNT,HOF,0,NOT
4277,hasoc_hi_6812,"अजहर मसूद को आतंकवादी “घोषित” करवा देना,मोदी स...",HOF,OFFN,UNT,HOF,0,NOT
4281,hasoc_hi_4334,भैया जी उत्तर प्रदेश के हर जिले के जो जिला अध्...,HOF,OFFN,UNT,HOF,0,NOT
4561,hasoc_hi_5700,अंडरवर्ल्ड डॉन दाऊद इब्राहिम को लेकर पाकिस्तान...,HOF,OFFN,UNT,HOF,0,NOT

In [14]:
train_df[train_df['Mismatch'] == 1].head(10)

,text_id,tweet,Original_label,task_2,task_3,New_label,Mismatch,New_label_iter2
11,hasoc_hi_288,गाये के नाम पर जुल्म करने वालों तुम्हारी औकात ...,NOT,NONE,NONE,HOF,1,NaN
99,hasoc_hi_495,मुस्लिम लोगों से वोट मांगने वाली पार्टियां क्य...,NOT,NONE,NONE,HOF,1,NaN
101,hasoc_hi_5808,बुर्का भी केवल लाचार मुस्लिम औरतों के लिए है। ...,NOT,NONE,NONE,HOF,1,NaN
121,hasoc_hi_4608,एसे #नीच और #घटिया लोगो को #चौराहे पर सबके स...,HOF,OFFN,TIN,NOT,1,NaN
271,hasoc_hi_767,अपने विष्लेसण की पुड़िया बना लो और इसको अपने *...,NOT,NONE,NONE,HOF,1,NaN
405,hasoc_hi_5113,किसी राष्ट्र के प्रधानमंत्री के लिए अपशब्दों ग...,HOF,HATE,TIN,NOT,1,NaN
469,hasoc_hi_7232,#PMModi ने 25 जून को संसद में कहा कि #WaterCri...,HOF,HATE,TIN,NOT,1,NaN
470,hasoc_hi_404,"#AIMIM Chief @asadowaisi says to the Chair, '...",HOF,HATE,TIN,NOT,1,NaN
472,hasoc_hi_664,हनीप्रीत बिना पापा #RamRahim को खेतो में रोटी ...,HOF,HATE,TIN,NOT,1,NaN
538,hasoc_hi_5778,चाट ते रहो चाट ते रहो चाट ते रहो चाट ते रहोच...,NOT,NONE,NONE,HOF,1,NaN

In [15]:
train_df["New_label_iter2"].value_counts()

New_label_iter2
NOT    39
HOF    11
Name: count, dtype: int64

Filling the empty value in New_label_iter2

In [16]:
train_df["New_label_iter2"] = train_df["New_label_iter2"].fillna(train_df["New_label"])
#The New_label_iter2 column stores relabeled annotations from iteration 2. For tweets that were not relabeled in this iteration, the values from the New_label column are copied into New_label_iter2.

In [17]:
train_df[train_df['Mismatch'] == 1].head(10)
#Top 10 rows of relabelled iteration1 (mismatch=1, at this stage) to check whether New_label is assigned to empty values in New_label_iter2.

,text_id,tweet,Original_label,task_2,task_3,New_label,Mismatch,New_label_iter2
11,hasoc_hi_288,गाये के नाम पर जुल्म करने वालों तुम्हारी औकात ...,NOT,NONE,NONE,HOF,1,HOF
99,hasoc_hi_495,मुस्लिम लोगों से वोट मांगने वाली पार्टियां क्य...,NOT,NONE,NONE,HOF,1,HOF
101,hasoc_hi_5808,बुर्का भी केवल लाचार मुस्लिम औरतों के लिए है। ...,NOT,NONE,NONE,HOF,1,HOF
121,hasoc_hi_4608,एसे #नीच और #घटिया लोगो को #चौराहे पर सबके स...,HOF,OFFN,TIN,NOT,1,NOT
271,hasoc_hi_767,अपने विष्लेसण की पुड़िया बना लो और इसको अपने *...,NOT,NONE,NONE,HOF,1,HOF
405,hasoc_hi_5113,किसी राष्ट्र के प्रधानमंत्री के लिए अपशब्दों ग...,HOF,HATE,TIN,NOT,1,NOT
469,hasoc_hi_7232,#PMModi ने 25 जून को संसद में कहा कि #WaterCri...,HOF,HATE,TIN,NOT,1,NOT
470,hasoc_hi_404,"#AIMIM Chief @asadowaisi says to the Chair, '...",HOF,HATE,TIN,NOT,1,NOT
472,hasoc_hi_664,हनीप्रीत बिना पापा #RamRahim को खेतो में रोटी ...,HOF,HATE,TIN,NOT,1,NOT
538,hasoc_hi_5778,चाट ते रहो चाट ते रहो चाट ते रहो चाट ते रहोच...,NOT,NONE,NONE,HOF,1,HOF

In [18]:
train_df.loc[train_df.index.isin(double_hate_ids)]
#Display the relabeled iteration-2 hate values (New_label_iter2) to check whether they are correct and did not altered by the existing New_label values.”
#new_label_iter2 (relabelled iteration2) should be different from New_label(relabelled iteration1)
#mismatch column values have not yet been updates, so all rows have value=0

,text_id,tweet,Original_label,task_2,task_3,New_label,Mismatch,New_label_iter2
1439,hasoc_hi_7629,#बाॅर्डर पर क्या खूब कहा हमारे जवान ने पाक जवा...,NOT,NONE,NONE,NOT,0,HOF
2417,hasoc_hi_2388,कल जो दिल्ली में ये मुल्ला लोग मन्दिर में घुस ...,NOT,NONE,NONE,NOT,0,HOF
2504,hasoc_hi_4262,लेकिन एक बात पर विश्वास हो गया कि मणिशंकर अय्य...,NOT,NONE,NONE,NOT,0,HOF
2758,hasoc_hi_3629,आज भी #मोदी #नीच आदमी है:- #मणिशंकर_अय्यर वो ...,NOT,NONE,NONE,NOT,0,HOF
2766,hasoc_hi_3825,आज ये बात पक्की हो गई कि #भडवा कलर sorry #भगवा...,NOT,NONE,NONE,NOT,0,HOF
2782,hasoc_hi_4418,"कोई #मस्जिद टूटी होती तो कांग्रेस,विपक्ष,पाकि...",NOT,NONE,NONE,NOT,0,HOF
3221,hasoc_hi_7269,एक बात और बताऊँ। कोई अगर इसको आंटी बोल देता है...,NOT,NONE,NONE,NOT,0,HOF
3472,hasoc_hi_725,चर्च पर पत्थर फेंका किसी ने तो UN तक दौड़े जाए...,NOT,NONE,NONE,NOT,0,HOF
3749,hasoc_hi_4186,"#शेरो के काफिले में #कुत्ते अच्छे नही लगते, #...",NOT,NONE,NONE,NOT,0,HOF
4376,hasoc_hi_4796,18 साल का सैनिक शहीद हुआ तो वह बच्चा नहीं था औ...,NOT,NONE,NONE,NOT,0,HOF
4422,hasoc_hi_2426,"#प्रज्ञा_ठाकुर का पुतला जलाना ही पड़ेगा अब, बह...",NOT,NONE,NONE,NOT,0,HOF

Finding the disagreement tweets

In [19]:
train_df['Mismatch'] = (
    (train_df['Original_label'] != train_df['New_label_iter2']) |
    (train_df['Original_label'] != train_df['New_label'])
).astype(int)

In [20]:
mismatch_count = (train_df["Mismatch"] == 1).sum()
print("Count of relabelled tweets after iteration1 and iteration2",mismatch_count)

Count of relabelled tweets after iteration1 and iteration2 375

Saving the dataset to the file

In [21]:
train_df.to_csv("dataset/Hindi_alltasks_iteration2label.csv",index=False)

Miscellanous code

In [22]:
final_rows = train_df.loc[
    train_df.index.isin(double_hate_ids) &
    (train_df["Mismatch"] == 0)
]

In [23]:
final_rows2 = train_df.loc[
    train_df.index.isin(double_nonhate_ids) &
    (train_df["Mismatch"] == 0)
]

In [24]:
print("hate ids\n")
print(final_rows)

#Empty final rows indicate that all tweet IDs from the relabeled dataset have different original and new labels (iteration2) in the training dataset; that is, they all have a mismatch value of 1.

hate ids

Empty DataFrame
Columns: [text_id, tweet, Original_label, task_2, task_3, New_label, Mismatch, New_label_iter2]
Index: []

In [25]:
print("non-hate ids.\n")
print(final_rows2)
#Empty final rows indicate that all tweet IDs from the relabeled dataset have different original and new labels(iteration2) in the training dataset; that is, they all have a mismatch value of 1.

non-hate ids.

Empty DataFrame
Columns: [text_id, tweet, Original_label, task_2, task_3, New_label, Mismatch, New_label_iter2]
Index: []